<?php

namespace Database\Seeders;

use App\Models\Continent;
use App\Models\country;
use Illuminate\Database\Seeder;

class ContinentAndCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seed continents
        $continents = [
            ['name' => 'Afrique'],
            ['name' => 'Antarctique'],
            ['name' => 'Asie'],
            ['name' => 'Europe'],
            ['name' => 'Amérique du Nord'],
            ['name' => 'Océanie'],
            ['name' => 'Amérique du Sud']
        ];

        foreach ($continents as $continentData) {
            Continent::updateOrCreate($continentData);
        }

        // Seed countries with corresponding continent IDs
        $countries = [
            // Africa
            ['name' => 'Algérie', 'continent_id' => 1],
            ['name' => 'Afrique du Sud', 'continent_id' => 1],
            ['name' => 'Angola', 'continent_id' => 1],
            ['name' => 'Bénin', 'continent_id' => 1],
            ['name' => 'Botswana', 'continent_id' => 1],
            ['name' => 'Burkina Faso', 'continent_id' => 1],
            ['name' => 'Burundi', 'continent_id' => 1],
            ['name' => 'Cameroun', 'continent_id' => 1],
            ['name' => 'Cap-Vert', 'continent_id' => 1],
            ['name' => 'République centrafricaine', 'continent_id' => 1],
            ['name' => 'Tchad', 'continent_id' => 1],
            ['name' => 'Comores', 'continent_id' => 1],
            ['name' => 'République du Congo', 'continent_id' => 1],
            ['name' => 'République démocratique du Congo', 'continent_id' => 1],
            ['name' => 'Côte d\'Ivoire', 'continent_id' => 1],
            ['name' => 'Djibouti', 'continent_id' => 1],
            ['name' => 'Égypte', 'continent_id' => 1],
            ['name' => 'Guinée équatoriale', 'continent_id' => 1],
            ['name' => 'Érythrée', 'continent_id' => 1],
            ['name' => 'Eswatini', 'continent_id' => 1],
            ['name' => 'Éthiopie', 'continent_id' => 1],
            ['name' => 'Gabon', 'continent_id' => 1],
            ['name' => 'Gambie', 'continent_id' => 1],
            ['name' => 'Ghana', 'continent_id' => 1],
            ['name' => 'Guinée', 'continent_id' => 1],
            ['name' => 'Guinée-Bissau', 'continent_id' => 1],
            ['name' => 'Kenya', 'continent_id' => 1],
            ['name' => 'Lesotho', 'continent_id' => 1],
            ['name' => 'Libéria', 'continent_id' => 1],
            ['name' => 'Libye', 'continent_id' => 1],
            ['name' => 'Madagascar', 'continent_id' => 1],
            ['name' => 'Malawi', 'continent_id' => 1],
            ['name' => 'Mali', 'continent_id' => 1],
            ['name' => 'Mauritanie', 'continent_id' => 1],
            ['name' => 'Maurice', 'continent_id' => 1],
            ['name' => 'Maroc', 'continent_id' => 1],
            ['name' => 'Mozambique', 'continent_id' => 1],
            ['name' => 'Namibie', 'continent_id' => 1],
            ['name' => 'Niger', 'continent_id' => 1],
            ['name' => 'Nigeria', 'continent_id' => 1],
            ['name' => 'Ouganda', 'continent_id' => 1],
            ['name' => 'Rwanda', 'continent_id' => 1],
            ['name' => 'Sao Tomé-et-Principe', 'continent_id' => 1],
            ['name' => 'Sénégal', 'continent_id' => 1],
            ['name' => 'Seychelles', 'continent_id' => 1],
            ['name' => 'Sierra Leone', 'continent_id' => 1],
            ['name' => 'Somalie', 'continent_id' => 1],
            ['name' => 'Soudan', 'continent_id' => 1],
            ['name' => 'Soudan du Sud', 'continent_id' => 1],
            ['name' => 'Tanzanie', 'continent_id' => 1],
            ['name' => 'Togo', 'continent_id' => 1],
            ['name' => 'Tunisie', 'continent_id' => 1],
            ['name' => 'Zambie', 'continent_id' => 1],
            ['name' => 'Zimbabwe', 'continent_id' => 1],


            // Asia
            ['name' => 'Afghanistan', 'continent_id' => 3],
            ['name' => 'Arabie saoudite', 'continent_id' => 3],
            ['name' => 'Arménie', 'continent_id' => 3],
            ['name' => 'Azerbaïdjan', 'continent_id' => 3],
            ['name' => 'Bahreïn', 'continent_id' => 3],
            ['name' => 'Bangladesh', 'continent_id' => 3],
            ['name' => 'Bhoutan', 'continent_id' => 3],
            ['name' => 'Birmanie', 'continent_id' => 3],
            ['name' => 'Brunei', 'continent_id' => 3],
            ['name' => 'Cambodge', 'continent_id' => 3],
            ['name' => 'Chine', 'continent_id' => 3],
            ['name' => 'Corée du Nord', 'continent_id' => 3],
            ['name' => 'Corée du Sud', 'continent_id' => 3],
            ['name' => 'Émirats arabes unis', 'continent_id' => 3],
            ['name' => 'Géorgie', 'continent_id' => 3],
            ['name' => 'Inde', 'continent_id' => 3],
            ['name' => 'Indonésie', 'continent_id' => 3],
            ['name' => 'Iran', 'continent_id' => 3],
            ['name' => 'Irak', 'continent_id' => 3],
            ['name' => 'Israël', 'continent_id' => 3],
            ['name' => 'Japon', 'continent_id' => 3],
            ['name' => 'Jordanie', 'continent_id' => 3],
            ['name' => 'Kazakhstan', 'continent_id' => 3],
            ['name' => 'Kirghizistan', 'continent_id' => 3],
            ['name' => 'Koweït', 'continent_id' => 3],
            ['name' => 'Laos', 'continent_id' => 3],
            ['name' => 'Liban', 'continent_id' => 3],
            ['name' => 'Malaisie', 'continent_id' => 3],
            ['name' => 'Maldives', 'continent_id' => 3],
            ['name' => 'Mongolie', 'continent_id' => 3],
            ['name' => 'Népal', 'continent_id' => 3],
            ['name' => 'Oman', 'continent_id' => 3],
            ['name' => 'Ouzbékistan', 'continent_id' => 3],
            ['name' => 'Pakistan', 'continent_id' => 3],
            ['name' => 'Palestine', 'continent_id' => 3],
            ['name' => 'Philippines', 'continent_id' => 3],
            ['name' => 'Qatar', 'continent_id' => 3],
            ['name' => 'Russie', 'continent_id' => 3],
            ['name' => 'Singapour', 'continent_id' => 3],
            ['name' => 'Sri Lanka', 'continent_id' => 3],
            ['name' => 'Syrie', 'continent_id' => 3],
            ['name' => 'Tadjikistan', 'continent_id' => 3],
            ['name' => 'Thaïlande', 'continent_id' => 3],
            ['name' => 'Timor oriental', 'continent_id' => 3],
            ['name' => 'Turkménistan', 'continent_id' => 3],
            ['name' => 'Turquie', 'continent_id' => 3],
            ['name' => 'Viêt Nam', 'continent_id' => 3],
            ['name' => 'Yémen', 'continent_id' => 3],

            // Europe
            ['name' => 'Albanie', 'continent_id' => 4],
            ['name' => 'Allemagne', 'continent_id' => 4],
            ['name' => 'Andorre', 'continent_id' => 4],
            ['name' => 'Autriche', 'continent_id' => 4],
            ['name' => 'Belgique', 'continent_id' => 4],
            ['name' => 'Biélorussie', 'continent_id' => 4],
            ['name' => 'Bosnie-Herzégovine', 'continent_id' => 4],
            ['name' => 'Bulgarie', 'continent_id' => 4],
            ['name' => 'Chypre', 'continent_id' => 4],
            ['name' => 'Croatie', 'continent_id' => 4],
            ['name' => 'Danemark', 'continent_id' => 4],
            ['name' => 'Espagne', 'continent_id' => 4],
            ['name' => 'Estonie', 'continent_id' => 4],
            ['name' => 'Finlande', 'continent_id' => 4],
            ['name' => 'France', 'continent_id' => 4],
            ['name' => 'Grèce', 'continent_id' => 4],
            ['name' => 'Hongrie', 'continent_id' => 4],
            ['name' => 'Islande', 'continent_id' => 4],
            ['name' => 'Irlande', 'continent_id' => 4],
            ['name' => 'Italie', 'continent_id' => 4],
            ['name' => 'Kosovo', 'continent_id' => 4],
            ['name' => 'Lettonie', 'continent_id' => 4],
            ['name' => 'Liechtenstein', 'continent_id' => 4],
            ['name' => 'Lituanie', 'continent_id' => 4],
            ['name' => 'Luxembourg', 'continent_id' => 4],
            ['name' => 'Malte', 'continent_id' => 4],
            ['name' => 'Moldavie', 'continent_id' => 4],
            ['name' => 'Monaco', 'continent_id' => 4],
            ['name' => 'Monténégro', 'continent_id' => 4],
            ['name' => 'Norvège', 'continent_id' => 4],
            ['name' => 'Pays-Bas', 'continent_id' => 4],
            ['name' => 'Pologne', 'continent_id' => 4],
            ['name' => 'Portugal', 'continent_id' => 4],
            ['name' => 'République tchèque', 'continent_id' => 4],
            ['name' => 'Roumanie', 'continent_id' => 4],
            ['name' => 'Royaume-Uni', 'continent_id' => 4],
            ['name' => 'Russie', 'continent_id' => 4],
            ['name' => 'Saint-Marin', 'continent_id' => 4],
            ['name' => 'Serbie', 'continent_id' => 4],
            ['name' => 'Slovaquie', 'continent_id' => 4],
            ['name' => 'Slovénie', 'continent_id' => 4],
            ['name' => 'Suède', 'continent_id' => 4],
            ['name' => 'Suisse', 'continent_id' => 4],
            ['name' => 'Ukraine', 'continent_id' => 4],

            // North America
            ['name' => 'Antigua-et-Barbuda', 'continent_id' => 5],
            ['name' => 'Bahamas', 'continent_id' => 5],
            ['name' => 'Barbade', 'continent_id' => 5],
            ['name' => 'Belize', 'continent_id' => 5],
            ['name' => 'Canada', 'continent_id' => 5],
            ['name' => 'Costa Rica', 'continent_id' => 5],
            ['name' => 'Cuba', 'continent_id' => 5],
            ['name' => 'Dominique', 'continent_id' => 5],
            ['name' => 'République dominicaine', 'continent_id' => 5],
            ['name' => 'Salvador', 'continent_id' => 5],
            ['name' => 'Grenade', 'continent_id' => 5],
            ['name' => 'Guatemala', 'continent_id' => 5],
            ['name' => 'Haïti', 'continent_id' => 5],
            ['name' => 'Honduras', 'continent_id' => 5],
            ['name' => 'Jamaïque', 'continent_id' => 5],
            ['name' => 'Mexique', 'continent_id' => 5],
            ['name' => 'Nicaragua', 'continent_id' => 5],
            ['name' => 'Panama', 'continent_id' => 5],
            ['name' => 'Saint-Christophe-et-Niévès', 'continent_id' => 5],
            ['name' => 'Sainte-Lucie', 'continent_id' => 5],
            ['name' => 'Saint-Vincent-et-les-Grenadines', 'continent_id' => 5],
            ['name' => 'Trinité-et-Tobago', 'continent_id' => 5],
            ['name' => 'États-Unis', 'continent_id' => 5],

            // Oceania
            ['name' => 'Australie', 'continent_id' => 6],
            ['name' => 'Fidji', 'continent_id' => 6],
            ['name' => 'Kiribati', 'continent_id' => 6],
            ['name' => 'Marshall', 'continent_id' => 6],
            ['name' => 'Micronésie', 'continent_id' => 6],
            ['name' => 'Nauru', 'continent_id' => 6],
            ['name' => 'Nouvelle-Zélande', 'continent_id' => 6],
            ['name' => 'Palaos', 'continent_id' => 6],
            ['name' => 'Papouasie-Nouvelle-Guinée', 'continent_id' => 6],
            ['name' => 'Salomon', 'continent_id' => 6],
            ['name' => 'Samoa', 'continent_id' => 6],
            ['name' => 'Tonga', 'continent_id' => 6],
            ['name' => 'Tuvalu', 'continent_id' => 6],
            ['name' => 'Vanuatu', 'continent_id' => 6],

            // South America
            ['name' => 'Argentine', 'continent_id' => 7],
            ['name' => 'Bolivie', 'continent_id' => 7],
            ['name' => 'Brésil', 'continent_id' => 7],
            ['name' => 'Chili', 'continent_id' => 7],
            ['name' => 'Colombie', 'continent_id' => 7],
            ['name' => 'Équateur', 'continent_id' => 7],
            ['name' => 'Guyana', 'continent_id' => 7],
            ['name' => 'Paraguay', 'continent_id' => 7],
            ['name' => 'Pérou', 'continent_id' => 7],
            ['name' => 'Suriname', 'continent_id' => 7],
            ['name' => 'Uruguay', 'continent_id' => 7],
            ['name' => 'Venezuela', 'continent_id' => 7],
        ];


        foreach ($countries as $countryData) {
            Country::updateOrCreate($countryData);
        }
    }

}
